### ISSUE TITLE
Handling of "/%postname%/" permalinks

### ISSUE THREAD

**Issue by nikolov-tmw** [nikolov-tmw/multilingual-wp#31]
By default WordPress would run a second query on 404 errors when the above structure is used for posts permalinks - that's because both pages and posts have the same permalink structure, so collisions may happen. 

I have to re-create this second query in the plugin when the above permalink structure is used.

**Comment by cocotton** [comment]
Hey Niko,

Just saw that you added the code to handle the /%postname% issue. You are a
beast, thx :) !

2013/6/28 Nikola Nikolov notifications@github.com

**Comment by nikolov-tmw** [comment]
Actually I haven't yet :) You'll see a comment from the commit on this issue and it will also be closed instead of "Open" :) I'll hopefully do that soon though.

PS: What you got was the notification about the new issue - I assume you'll get a notification when it's closed or when a new comment is added, so look for that.

**Comment by cocotton** [comment]
Oh doh! My bad haha ;)

2013/7/3 Nikola Nikolov notifications@github.com
