### ISSUE TITLE
Front static page problem

### ISSUE THREAD

**Issue by iggyzz** [nikolov-tmw/multilingual-wp#33]
Any front page that I set in Reading setting as static is not displayed for me and it is not in menu, either. Instead, Your latest site content post is shown.
I use English, Czech - default, Slovak languages.

**Comment by nikolov-tmw** [comment]
Hi,

Thanks for submitting this issue. I'm on sort of a vacation at the moment
and I have kind of bad internet connection, so I will probably be able to
check it on Thursday the soonest.

**Comment by nikolov-tmw** [comment]
Thanks again for submitting the issue - I finally got around and found some time to fix this problem. 

You can download the fixed version from here(zip) - https://github.com/nikolov-tmw/multilingual-wp/archive/master.zip or here(tar.gz) - https://github.com/nikolov-tmw/multilingual-wp/archive/master.tar.gz

**Comment by iggyzz** [comment]
Thanks for finding time to help me and for fixing this issue. But...:
When I update plugin (deactivated, update via ftp, reactivate) and set static page, then static page is displayed correctly, but in menu were duplicated items - in actual language + some from other languages, too. I tried to fix it and remove menu structure in Appearance - Menus. Duplicated items are out, bud pages are not accessible, when plugin is active. When deactivated, pages are accessible correctly.

**Comment by nikolov-tmw** [comment]
That's quite strange. Can you possibly go to Settings > Permalinks in order for the permalink structure to be re-built and see if that helps? 

It's strange that the items were duplicated though.

**Comment by iggyzz** [comment]
I tried to switch permalinks to Numeric, then this appeared:
This is somewhat embarrassing, isn’t it?
It seems we can’t find what you’re looking for. Perhaps searching can help.
After switching back to default it displayed nothing as before - pages were not accessible.
Can you please have a look at it? I will send you login to email.

**Comment by nikolov-tmw** [comment]
Sure send me an email at nikolov.tmw@gmail.com
