### ISSUE TITLE
convert_URL does not translate the actual slug

### ISSUE THREAD

**Issue by scherii** [nikolov-tmw/multilingual-wp#37]
In my tests `mlwp_convert_URL()` would not translate the slug-part of the URL correctly.

For example:
`mlwp_convert_URL( 'http://example.com/freunde', 'en')`

… _should_ convert the URL to `http://example.com/en/friends`

Instead it gives me this: `http://example.com/en/freunde`

**Comment by nikolov-tmw** [comment]
This is because of the way Multilingual_WP::convert_URL() works. 

Generally post/page permalinks are converted using Multilingual_WP::convert_post_URL() instead. Which in your case might still not work. 

What are you trying to achieve? 

I was initially going to add support for getting post id's by URL, but I feel like that could make things slower.

**Comment by scherii** [comment]
I have a custom meta box with a url field in which users can enter a redirect URL in case the post teaser should not link to the post itself.

Here you can see it live: http://walserhof.ch/
There is a sidebar that slides in which displays the latest posts. Some of the posts are linked to their post content and some should be redirected to a specific post or page. In this case a user is able to provide the redirect URL.
Instead of putting another field in there I first thought that a simple convert_URL or convert_post_URL function would do it. Unfortunately it doesn't work – so maybe instead I will rewrite the meta box to contain a dropdown of pages.

As with the other issue… no hurry! I just noticed that it does not do what I thought it would :smile:

And as far as our sites are concerned – speed is not an issue for we use caching (Cachify).

**Comment by nikolov-tmw** [comment]
For now the best way is indeed to use a drop-down with all posts/pages. If there will be a lot of content, a more complicated solution would be to show a pop-up where the user would be able to search for the post/page in question(similar to how the "insert link" button works in the richtext editor) - more effort, but you won't have huge amounts of data within the drop-down. 

It makes sense to work, but it currently doesn't :( 

Well in your case it's ok, but one of the issues(among other ones) of qTranslate is that it slows-down most sites considerably so I want to make a more efficient version :smile:

I might poke around in the future and try to allow different languages for the convert_post_URL() function.
